# Generated by Django 2.0.2 on 2020-11-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', 'title'], 'verbose_name': 'página', 'verbose_name_plural': 'páginas'},
        ),
        migrations.RemoveField(
            model_name='page',
            name='Content',
        ),
        migrations.AddField(
            model_name='page',
            name='content',
            field=models.TextField(default=0, verbose_name='Contenido'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
